{
 "title": "Spark_Window",
 "description": "【English version】Update 2023.12.22,  Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics",
 "tags": [
  "Prometheus",
  "windows_exporter",
  "redis",
  "python-metric",
  "dotnet_app"
 ],
 "time": { "from": "2025-08-21T10:20:27.690Z", "to": "2025-08-21T10:50:27.690Z" },
 "templating": {
  "list": [
   {
    "name": "Windows_instance",
    "label": "Windows_exporter",
    "query": {
     "query": "label_values(up{job=\"windows_nodes\"},instance)"
    }
   },
   {
    "name": "Redis_instance",
    "label": "Redis_exporter",
    "query": {
     "query": "label_values(up{job=\"redis\"},instance)"
    }
   },
   {
    "name": "Python_instance",
    "label": "Python_exporter",
    "query": {
     "query": "label_values(up{job=\"python-metrics\"},instance)"
    }
   },
   {
    "name": "Net_instance",
    "label": ".Net_exporter",
    "query": {
     "query": "label_values(up{job=\"dotnet_app\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Overview ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Resources Overview : ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"windows_nodes\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=\"windows_nodes\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "windows_cs_logical_processors{job=\"windows_nodes\"} - 0",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{job=\"windows_nodes\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU usage%"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"windows_nodes\"} - 0",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=\"windows_nodes\"} / windows_cs_physical_memory_bytes{job=\"windows_nodes\"}",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=\"windows_nodes\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=\"windows_nodes\",volume=~\"C:\"})",
     "legendFormat": "C:/ Drive Usage"
    },
    {
     "expr": "max by (instance) (1 - windows_logical_disk_free_bytes{job=\"windows_nodes\", volume=~\".:\"}/windows_logical_disk_size_bytes{job=\"windows_nodes\", volume=~\".:\"})",
     "legendFormat": "Partition Used%"
    },
    {
     "expr": "windows_os_processes{job=\"windows_nodes\"}",
     "legendFormat": "No of processes"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=\"windows_nodes\",state=~\"running\"})",
     "legendFormat": "Running Services"
    },
    {
     "expr": "max(rate(windows_logical_disk_read_bytes_total{job=\"windows_nodes\", volume=~\".:\"}[2m])) by (instance)",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "max(rate(windows_logical_disk_write_bytes_total{job=\"windows_nodes\", volume=~\".:\"}[2m])) by (instance)",
     "legendFormat": "Disk Write"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - windows_system_system_up_time{job=\"windows_nodes\", instance=~\"$Windows_instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=\"windows_nodes\",instance=~\"$Windows_instance\",mode=\"idle\"}[2m])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage rate by partition",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=\"windows_nodes\", instance=~\"$Windows_instance\", volume=~\".:\"} / windows_logical_disk_size_bytes{job=\"windows_nodes\", instance=~\"$Windows_instance\", volume=~\".:\"}) * 100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{job=\"windows_nodes\", instance=~\"$Windows_instance\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_processes{job=\"windows_nodes\",instance=~\"$Windows_instance\"}",
     "legendFormat": "Number of processes"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=\"windows_nodes\",instance=~\"$Windows_instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"} / windows_cs_physical_memory_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"})*100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"} / windows_cs_physical_memory_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"})*100",
     "legendFormat": "Memory Usage "
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_cs_physical_memory_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Physical Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Physical Memory Remaining",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_virtual_memory_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\"}",
     "legendFormat": "Free Virtual Memory"
    }
   ]
  },
  {
   "title": "Disk space remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\", volume=~\".:\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Space remaining {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{job=\"windows_nodes\",instance=~\"$Windows_instance\", volume=~\".:\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Space {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=\"windows_nodes\",instance=~\"$Windows_instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{job=\"windows_nodes\",instance=~\"$Windows_instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{job=\"windows_nodes\",instance=~\"$Windows_instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_reads_total{job=\"windows_nodes\",instance=~\"$Windows_instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_writes_total{job=\"windows_nodes\",instance=~\"$Windows_instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{job=\"windows_nodes\",instance=~\"$Windows_instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "System Threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Number of Sockets Open",
   "type": "timeseries",
   "description": "ipv4+ipv6",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "sum(windows_tcp_connections_established{job=\"windows_nodes\", instance=~\"$Windows_instance\"})",
     "legendFormat": "Socket Open"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_sent_total{job=\"windows_nodes\",instance=~\"$Windows_instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8 > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent-Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_received_total{job=\"windows_nodes\",instance=~\"$Windows_instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received-Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Python and Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Redis Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 40 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{job=\"redis\",instance=~\"$Redis_instance\"}"
    }
   ]
  },
  {
   "title": "Redis Peak Memory (Since Start)",
   "type": "stat",
   "description": "Highest amount of memory Redis has used since it started.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_peak_bytes{job=\"redis\",instance=~\"$Redis_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Memory Used",
   "type": "timeseries",
   "description": "Total Memory currently used by the Redis server, measured in MB.",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"redis\",instance=~\"$Redis_instance\"} / 1024 / 1024",
     "legendFormat": "Redis Memory"
    }
   ]
  },
  {
   "title": "Python GC Objects Collected",
   "type": "bargauge",
   "description": "total number of objects collected (cleaned up) by the garbage collector for each generation (0, 1, or 2).",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{job=\"python-metrics\",instance=~\"$Python_instance\"}",
     "legendFormat": "Generation {{generation}} - {{__field__}}"
    }
   ]
  },
  {
   "title": "Python memory Leak",
   "type": "timeseries",
   "description": "Rate of change (increase or decrease) of memory usage by the Python process over the last 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "deriv(python_process_memory_bytes{job=\"python-metrics\",instance=~\"$Python_instance\"}[5m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Redis uptime",
   "type": "stat",
   "description": "how long Redis has been running since the last start.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{job=\"redis\",instance=~\"$Redis_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Redis Connection",
   "type": "stat",
   "description": "how many clients are currently connected to the Redis server",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"redis\",instance=~\"$Redis_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python GC Objects Uncollected",
   "type": "bargauge",
   "description": "total number of objects that could not be collected (possibly memory leaks) for each GC generation.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{job=\"python-metrics\",instance=~\"$Python_instance\"}",
     "legendFormat": "Generation {{generation}} - {{__field__}}"
    }
   ]
  },
  { "title": ".NET Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Active CLR memory Usage",
   "type": "timeseries",
   "description": "Current size of the managed heap (in MB), i.e., how much memory is in use by .NET objects (post-GC).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "system_runtime_gc_heap_size{job=\"dotnet_app\",instance=~\"$Net_instance\"}",
     "legendFormat": "Active Clear Memory"
    }
   ]
  },
  {
   "title": "Threads in pool",
   "type": "timeseries",
   "description": "The current number of threads in the thread pool (worker + I/O threads).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "system_runtime_threadpool_thread_count{job=\"dotnet_app\",instance=~\"$Net_instance\"}",
     "legendFormat": "Threads in pool"
    }
   ]
  },
  {
   "title": "Active SQL connections",
   "type": "timeseries",
   "description": "Current number of active SQL connections your .NET app is holding at the time of the scrape.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "db_connection_pool_active{job=\"dotnet_app\",instance=~\"$Net_instance\"}",
     "legendFormat": "Current Connection"
    }
   ]
  },
  {
   "title": "API response Time",
   "type": "timeseries",
   "description": "Maximum response time for 95% of API requests over the past 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}